// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://keewplijcxasxfiwccgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlZXdwbGlqY3hhc3hmaXdjY2dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTQzMDksImV4cCI6MjA2NTU5MDMwOX0.1TZjjJnKhjHws2Qs5Zurg3ECryNDd1lNtADqaZDbw0s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);